### ISSUE TITLE
Use google provided Empty type 

### ISSUE THREAD

**Issue by curtpm** [ynqa/faiss-server#1]
I see you are using a custom message type as the request type to:

message HealthCheckRequest {};

rpc HealthCheck (HealthCheckRequest) returns (HealthCheckResponse);

Assuming you never actually a need to add parms to this, you can use the Google Empty message type:

https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto

**Comment by ynqa** [comment]
@curtpm  Thanks for your issues. Yes, it's enough to use `Empty` for request. But I'd like to be consistent the notation of request/response. Which do you think good?

**Comment by curtpm** [comment]
i dont think either way is better than the other, if you want to keep thing more consistent with type names thats perfectly fine.

**Comment by ynqa** [comment]
@curtpm I see. So I will change to use `Empty`. Thanks.
